### ISSUE TITLE
Local folder mods do not satisfy other mods dependencies

### ISSUE THREAD

**Issue by JonnyNova** [FluffierThanThou/ModManager#31]
This is a possible non-steam only issue. Local folder mods aren't checked if they satisfy another mod's dependency even if they have `About/PublishedFileId.txt` set.

**Comment by FluffierThanThou** [comment]
Could you provide some more details on when this happens? 

Identifying mods is a bit of a messy business, but all mods are matched to, in order;
1. identifier; this is really the folder name, for steam mods this corresponds to publishedFileId
2. mod name; the mods' name, with any spaces stripped out
3. manifest identifier; an identifier given in the mods' manifest. This should really be the preferred way to identify mods, but it depends on both mods' authors providing static and unique identifiers in their manifests.
