### ISSUE TITLE
Mods loaded above core aren't loaded correctly

### ISSUE THREAD

**Issue by XeoNovaDan** [FluffierThanThou/ModManager#32]
When saving a mod list which has mods that need to be loaded above Core to work properly (e.g Mod-E), saving is done correctly (as shown in the saved config XML file). However, when loading that mod list, mods that were saved above Core will instead be loaded just below core.

This is with the latest Steam version of Mod Manager as of the time of posting (v1.15.748, 2018-11-20).

**Comment by FluffierThanThou** [comment]
confirmed, investigating

**Comment by FluffierThanThou** [comment]
fixed
