### ISSUE TITLE
Mod Manager Only Shows Avaliable 

### ISSUE THREAD

**Issue by YungKlee** [FluffierThanThou/ModManager#34]
![20181209014739_1](https://user-images.githubusercontent.com/45758567/49730228-9786d200-fcdc-11e8-9b4a-6f4e09ea3de1.jpg)
__*If image above is unavaliable, here is a direct link to the source:_ 
https://steamcommunity.com/sharedfiles/filedetails/?id=1585450775_

**Problem:**
I recently subscribed to your mod and everything was working. Randomly one day the mod completely stopped functioning properly while I was trying to arrange my mod list. Now every time I enable Mod Manager (with and without additional mods) I don't get anything but a blank window with the 'Available' section, which is also just a blank box (as seen in picture)

**What I've Tried**
Changed Load Order
Restarted Steam
Restarted Computer
Fresh Install of Mod
Fresh Install of Rimworld

**Occurance date: 9th DEC 2018 (Time (approx): 01:00AM )**

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by DontStarve72** [comment]
I recently encountered this.
[output_log.txt](https://github.com/FluffierThanThou/ModManager/files/3155403/output_log.txt)
