### ISSUE TITLE
harmony.log.txt on desktop 1.15.751

### ISSUE THREAD

**Issue by stjabo** [FluffierThanThou/ModManager#36]
This file appears on my desktop when I run Rimworld.  Disabling Mod Manager makes it stop.

Just a heads-up.

Thanks for your awesome mods!

**Comment by FluffierThanThou** [comment]
Are you sure you're using the release version, and not a debug version? 

Harmony's debug flag is only set if the mod is compiled in debug mode, and the releases  are normally compiled in release mode.
https://github.com/FluffierThanThou/ModManager/blob/master/Source/ModManager/ModManager.cs#L14
