### ISSUE TITLE
design reference while making standalone version of the mod manager

### ISSUE THREAD

**Issue by zzzz465** [FluffierThanThou/ModManager#38]
Hi. I'm making an external tool for Rimworld ( like Skyrim LOOT )
I'm bit worry about using your mod manager design(layout, button style. etc...)
can I use(or reference) your mod manager design?

**Comment by FluffierThanThou** [comment]
Hey, sorry it took me so long to see this - but by all means, do what you wish with my code! 

If you end up using my code or taking a lot of inspiration from my UI, then you should mention me in the credits, but that's about it :).
