### ISSUE TITLE
loadAfter element in Manifest.xml doesn't seem to work

### ISSUE THREAD

**Issue by Nightliss** [FluffierThanThou/ModManager#42]
![image](https://user-images.githubusercontent.com/30467858/57579362-199d4180-749b-11e9-99ec-c82479ed81ad.png)

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<Manifest>
  <identifier>FastRegen_NanoTechRepair</identifier>
  <version>1.0.0</version>
  <dependencies>
    <li>NanoRepairTech</li>
    <li>Fastregen1.0</li>
  </dependencies>
  <loadAfter>
    <li>NanoRepairTech</li>
    <li>Fastregen1.0</li>
    <li>VanillaFurnitureExpanded-MedicalModule</li>
    <li>[sd]medicaddons</li>
    <li>MoreLinkables</li>
    <li>WallVitalsMonitor</li>
  </loadAfter>
</Manifest>
```

I should get a warning when I load my mod before the dependencies and those specified in loadAfter. Is it not working or am I missing something?

**Comment by FluffierThanThou** [comment]
that does appear to be a bug, I'll investigate. Thanks for reporting!

(note that you don't have to specify loadAfter for mods already listed as a dependency, load order is implied in these cases).

**Comment by FluffierThanThou** [comment]
thanks, I think this had been broken for a while, and you're the first one to notice...

**Comment by Nightliss** [comment]
or no one bothered to report it :P Thank you for fast fix!
