### ISSUE TITLE
mod menu not loading

### ISSUE THREAD

**Issue by mysticrage** [FluffierThanThou/ModManager#44]
i have a ton of other mods loaded up and it might be a pain to find im not really sure but all the mod does for me is i load it up it restarts the game i go to the mod menu again and it has the overlay for your mod but nothing at all loads and i cant exit out of the menu i have to exit the game from out of the game
[output_log.txt](https://github.com/FluffierThanThou/ModManager/files/3187776/output_log.txt)

**Comment by FluffierThanThou** [comment]
I'm not sure you sent me the right output_log. There's a bunch of serious errors in here (looks like you're trying to load old mods into the release version of the game), but none of it related to Mod Manager. 

Closing for now, feel free to reopen if you have more information.
