### ISSUE TITLE
GUI Error: GUIClips 

### ISSUE THREAD

**Issue by ThunderingDog** [FluffierThanThou/ModManager#45]
https://www.dropbox.com/s/z4z5awgh3wwtkjz/ModsConfig.xml.backup-20190516-1653?dl=0

Output logs and mod config load order

**Comment by FluffierThanThou** [comment]
Thanks for reporting! You don't seem to have included an output log, so I can't really see what's happening. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by ThunderingDog** [comment]
"https://www.dropbox.com/sh/gbpxp6q9buvtlnt/AAAXYt4wUk5rmSRyXq2GAHI6a?dl=0"

Sorry for the late Reply, Wierd i Tought that i added it in the first link Might have copy wrong Link, 
If That link i provided now dont work I think i managed to upload the output log here, dont know atm
Thank you For you time :)

[output_log.txt](https://github.com/FluffierThanThou/ModManager/files/3217889/output_log.txt)

**Comment by FluffierThanThou** [comment]
This looks similar to #46, which was just fixed. Feel free to reopen if it still occurs.
