### ISSUE TITLE
ModManager fails hard if unexpected files are present in the modlist dir

### ISSUE THREAD

**Issue by MollMastah** [FluffierThanThou/ModManager#46]
An issue popped up after i updated to unstable, and has persisted after trying to revert back to stable, having deleted the core file on both occasions to test this. The Mod Manager's UI is rendered as a Blank version of the Vanilla Mod menu UI.
Edit:
First one i uploaded was useless, Apologies.
[output_log.txt](https://github.com/FluffierThanThou/ModManager/files/3219897/output_log.txt)

**Comment by MollMastah** [comment]
Apologies, but i managed to fix the issue, turns out i'm just an idiot who loaded a Modconfig file in the Modlists Folder... Apologies for the Trouble.

**Comment by FluffierThanThou** [comment]
No worries! Issues that resolve themselves are the best kind of issues ;).

That said, ModManager crashing without any kind of feedback when invalid modlists are loaded _in the background_ is really shitty. I'm reopening this as a request for better error handling.

Thanks for reporting and updating the issue!
