### ISSUE TITLE
Fail to parse when there is no comparator

### ISSUE THREAD

**Issue by notfood** [FluffierThanThou/ModManager#50]
incompatibleWith is asking for version number when it doesn't need to.

```xml
  <incompatibleWith>
    <li>Unofficial Multiplayer API</li>
  </incompatibleWith>
```

![image](https://user-images.githubusercontent.com/5370107/59969925-bbdf2900-951f-11e9-87e5-b08841b5c072.png)

**Comment by FluffierThanThou** [comment]
The parsing is basic as heck, you're not supposed to ever have spaces in
the identifier. It's trying to parse 'Multiplayer' as the operator, and API
as a version number.
