### ISSUE TITLE
Settings reverting when updating local copies

### ISSUE THREAD

**Issue by Boodals** [FluffierThanThou/ModManager#52]
I ran into a bug where a bunch of my mod settings were reverting to older settings when updating mods set as local copies.
The only abnormality that I can think of is that I accidentally ran a few workshop mods as non-local copies when I first downloaded them, and configured them. But I can't remember if the particular mod i'm observing was one of them, so it could be unrelated.
In my config folder, I have two sets of config xml files, one prepended with `Mod___LocalCopy`, the other with `Mod_` followed by what I assume is the workshop ID. They have roughly the same number of files, so I assume its unrelated to the fact that I ran some as non-local copies, But it seems the local copy version is being reverted to the workshop version when I update mods.

**Comment by FluffierThanThou** [comment]
Ok, so what you're describing is pretty much working as intended. 

Whenever a copy is made (and 'updating' is really just making a new copy), the relevant settings file is copied from the source (workshop) mod. The main reason I do this is to maintain compatibility - a mod update may have changed the settings format, and invalidated the settings file. 

While writing this, I've realized that this same problem would also occur if the source mod was updated on steam, so handling settings format changes is really not something that Mod Manager needs to concern itself with. That also means that we should leave existing settings file in place. 

Thanks for bringing this to my attention!
