### ISSUE TITLE
Feature Request: Multi select & Mod list ordering

### ISSUE THREAD

**Issue by gooftroop** [FluffierThanThou/ModManager#53]
First off, love your work - this mod makes the entire game experience that much better, so thank you for your time and effort!
Would it be possible to add two features?

There have been many times I've wished I could shift+ click or ctl + click to select a group or multiple mods to add to the active list. Would it be possible to add this functionality? In lieu of that, or in addition to that, do you think there'd be value in adding a plus "+" button to the right side of a mod that allows users to click to add a mod to the active list (or a minus to remove it from the active list)? I think this would also help with the experience of adding/removing mods.

Secondly, the warning about mod order dependency is excellent. However, you only see if after adding a mod to the active list. Is it at all possible to do some sort of auto-ordering in the inactive mod list if a mod needs to be before another? Kind of a pre-emptive optimization that would drastically improve the user experience.

Thanks!

**Comment by FluffierThanThou** [comment]
Multi selecting is not likely, the whole code base is just not laid out for it.

Sorting by load order is not quite as simple as one might hope, but I've been looking at some ways to achieve this. I'm going to close this ticket and open a new one soon with my ideas for auto-ordering by (expected) load order.
